In [18]:
import numpy as np
import random
import operator
import pandas as pd
import matplotlib.pyplot as plt 

In [19]:
t = np.int_([3,8,4.5,6,4,4,3,3,3,2,7])

def generateBool():
    number = np.zeros((10), dtype=int)
    for i in range(10):
        number[i] = random.randrange(2)
    return number
    
def matrixGen():
    limit = np.zeros((11), dtype=int)
    matrix = np.zeros((10,11), dtype=int)
    for i in range(11):
        if (i==0):
            limit[i] = int(1290/t[i])
            for j in range(10):
                matrix[j,i] = random.randrange(limit[i])
                    
        elif (i==1):
            for j in range(10):
                limit[i] = int((1290-matrix[j,i-1]*t[i-1])/t[i])
                if (limit[i]==0):
                    continue
                matrix[j,i] = random.randrange(limit[i])
                
        elif (i==2):
            for j in range(10):
                limit[i] = int((1290-matrix[j,i-2]*t[i-2]-matrix[j,i-1]*t[i-1])/t[i])
                if (limit[i]==0):
                    continue
                matrix[j,i] = random.randrange(limit[i])
                
        elif (i==3):
            for j in range(10):
                limit[i] = int((1290-matrix[j,i-3]*t[i-3]-matrix[j,i-2]*t[i-2]-matrix[j,i-1]*t[i-1])/t[i])
                if (limit[i]==0):
                    continue
                matrix[j,i] = random.randrange(limit[i])
                
        elif (i==4):
            for j in range(10):
                limit[i] = int((1290-matrix[j,i-4]*t[i-4]-matrix[j,i-3]*t[i-3]-matrix[j,i-2]*t[i-2]-matrix[j,i-1]*t[i-1])/t[i])
                if (limit[i]==0):
                    continue
                matrix[j,i] = random.randrange(limit[i])
                
        elif (i==5):
            for j in range(10):
                limit[i] = int((1290-matrix[j,i-5]*t[i-5]-matrix[j,i-4]*t[i-4]-matrix[j,i-3]*t[i-3]-matrix[j,i-2]*t[i-2]-matrix[j,i-1]*t[i-1])/t[i])
                if (limit[i]==0):
                    continue
                matrix[j,i] = random.randrange(limit[i])
                
        elif (i==6):
            for j in range(10):
                limit[i] = int((1290-matrix[j,i-6]*t[i-6]-matrix[j,i-5]*t[i-5]-matrix[j,i-4]*t[i-4]-matrix[j,i-3]*t[i-3]-matrix[j,i-2]*t[i-2]-matrix[j,i-1]*t[i-1])/t[i])
                if (limit[i]==0):
                    continue
                matrix[j,i] = random.randrange(limit[i])
                
        elif (i==7):
            for j in range(10):
                limit[i] = int((1290-matrix[j,i-7]*t[i-7]-matrix[j,i-6]*t[i-6]-matrix[j,i-5]*t[i-5]-matrix[j,i-4]*t[i-4]-matrix[j,i-3]*t[i-3]-matrix[j,i-2]*t[i-2]-matrix[j,i-1]*t[i-1])/t[i])
                if (limit[i]==0):
                    continue
                matrix[j,i] = random.randrange(limit[i])
                
        elif (i==8):
            for j in range(10):
                limit[i] = int((1290-matrix[j,i-8]*t[i-8]-matrix[j,i-7]*t[i-7]-matrix[j,i-6]*t[i-6]-matrix[j,i-5]*t[i-5]-matrix[j,i-4]*t[i-4]-matrix[j,i-3]*t[i-3]-matrix[j,i-2]*t[i-2]-matrix[j,i-1]*t[i-1])/t[i])
                if (limit[i]==0):
                    continue
                matrix[j,i] = random.randrange(limit[i])
                
        elif (i==9):
            for j in range(10):
                limit[i] = int((1290-matrix[j,i-9]*t[i-9]-matrix[j,i-8]*t[i-8]-matrix[j,i-7]*t[i-7]-matrix[j,i-6]*t[i-6]-matrix[j,i-5]*t[i-5]-matrix[j,i-4]*t[i-4]-matrix[j,i-3]*t[i-3]-matrix[j,i-2]*t[i-2]-matrix[j,i-1]*t[i-1])/t[i])
                if (limit[i]==0):
                    continue
                matrix[j,i] = random.randrange(limit[i])
                
        elif (i==10):
            for j in range(10):
                limit[i] = int((1290-matrix[j,i-10]*t[i-10]-matrix[j,i-9]*t[i-9]-matrix[j,i-8]*t[i-8]-matrix[j,i-7]*t[i-7]-matrix[j,i-6]*t[i-6]-matrix[j,i-5]*t[i-5]-matrix[j,i-4]*t[i-4]-matrix[j,i-3]*t[i-3]-matrix[j,i-2]*t[i-2]-matrix[j,i-1]*t[i-1])/t[i])
                if (limit[i]==0):
                    continue
                matrix[j,i] = random.randrange(limit[i])
                    
    return matrix

In [20]:
Adef = np.int_([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1])
Bdef = np.int_([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])
size = 50

In [21]:
def generatePiece():
    A = generateBool()
    B = generateBool()
    C = generateBool()
    Aut_a = generateBool()
    Aut_b = generateBool()
    Aut_c = generateBool()
    
    Sa = np.multiply(Aut_a, A)
    Sb = np.multiply(Aut_b, B)
    Sc = np.multiply(Aut_c, C)
    
    sum_Sab = (np.sum(Sa) + np.sum(Sb))*(150000 + 380000)
    sum_Sc  = (np.sum(Sc))*(280000 + 380000)
    
    Na = A - Sa
    Nb = B - Sb
    Nc = C - Sc
    
    sum_Nab = (np.sum(Na) + np.sum(Nb))*150000
    sum_Nc  = np.sum(Nc) * 280000
    
    sum_SN = int((sum_Sab + sum_Sc + sum_Nab + sum_Nc)*0.015)
    
    matrixA = matrixGen()
    matrixB = matrixGen()
    matrixC = matrixGen()
    
    Op_Na = Na.dot(matrixA)
    Op_Nb = Nb.dot(matrixB)
    Op_Nc = Nc.dot(matrixC)
    
    Op_Sa = Sa.dot(matrixA)
    Op_Sb = Sb.dot(matrixB)
    Op_Sc = Sc.dot(matrixC)
    
    OpTOT = Op_Na + Op_Nb + Op_Nc + Op_Sa + Op_Sb + Op_Sc
    numA = np.zeros(10, dtype=int)
    numB = np.zeros(10, dtype=int)
    
    for i in range(10):
        if (i<9):
            numA[i] = int(OpTOT[i]/2)
            numB[i] = int(OpTOT[i]/2)
        elif (i == 10):
            numA[i] = OpTOT[i]
            numB[i] = OpTOT[i+1]
    numTOTA = min(numA)
    numTOTB = min(numB)
    
    TOp_Na = np.zeros(11, dtype=int)
    TOp_Nb = np.zeros(11, dtype=int)
    TOp_Nc = np.zeros(11, dtype=int)
    
    for k in range(11):
        TOp_Na[k] = Op_Na[k]*t[k]
        TOp_Nb[k] = Op_Nb[k]*t[k]
        TOp_Nc[k] = Op_Nc[k]*t[k]
    
    Parcial_Na = Adef.dot(TOp_Na)
    Parcial_Nb = Bdef.dot(TOp_Nb)
    Op_Sa = Adef.dot(Op_Sa)
    Op_Sb = Bdef.dot(Op_Sb)
    
    TOT_Na = np.sum(TOp_Na) + np.sum(Op_Sa)
    TOT_Nb = np.sum(TOp_Nb) + np.sum(Op_Sb)
    TOT_Nc = np.sum(TOp_Nc) + np.sum(Op_Sc)
    
    tempTOT = (TOT_Na + TOT_Nb + TOT_Nc)/(sum_SN)
    numT = int((TOT_Na + TOT_Nb + TOT_Nc)/(1290))
    
    if (tempTOT < 8*60):
        custoT = numT*6000
    elif (8*60 < tempTOT < 16*60):
        custoT = numT*8000
    elif (tempTOT > 16*60):
        custoT = numT*9000
    if (numTOTA + numTOTB == 0):
        custo_Prod = int((custoT + sum_SN)/(1*20))
    else:
        custo_Prod = int((custoT + sum_SN)/((numTOTA + numTOTB)*20))
    return custo_Prod, numTOTA, numTOTB

def generate_Parent():
    genes = np.zeros((size, 3))
    for i in range(size):
        genes[i, :] = generatePiece()
    return genes

In [43]:
genes = generate_Parent()
print(genes)

[[9052.    0.    0.]
 [6982.    0.    0.]
 [5422.    0.    0.]
 [4725.    0.    0.]
 [6457.    0.    0.]
 [8272.    0.    0.]
 [8520.    0.    0.]
 [7140.    0.    0.]
 [7927.    0.    0.]
 [5820.    0.    0.]
 [7530.    0.    0.]
 [6045.    0.    0.]
 [7155.    0.    0.]
 [7350.    0.    0.]
 [7065.    0.    0.]
 [5235.    0.    0.]
 [7492.    0.    0.]
 [7237.    0.    0.]
 [7875.    0.    0.]
 [6015.    0.    0.]
 [6390.    0.    0.]
 [8032.    0.    0.]
 [6330.    0.    0.]
 [5422.    0.    0.]
 [6855.    0.    0.]
 [9195.    0.    0.]
 [7087.    0.    0.]
 [4935.    0.    0.]
 [8145.    0.    0.]
 [5250.    0.    0.]
 [8902.    0.    0.]
 [8287.    0.    0.]
 [5962.    0.    0.]
 [8175.    0.    0.]
 [5535.    0.    0.]
 [5977.    0.    0.]
 [5947.    0.    0.]
 [9127.    0.    0.]
 [8542.    0.    0.]
 [7747.    0.    0.]
 [5722.    0.    0.]
 [7335.    0.    0.]
 [8302.    0.    0.]
 [3915.    0.    0.]
 [8190.    0.    0.]
 [5647.    0.    0.]
 [4357.    0.    0.]
 [5835.    0.

In [23]:
def rankFnc(genes):
    results = {}
    for i in range(size):
        if (genes[i,1] <75):
            results[i] = 1
        else:
            results[i] = 0
        results[i] += 1 - 1/genes[i,0]
    return sorted(results.items(), key = operator.itemgetter(1), reverse = False)

In [24]:
results = rankFnc(genes)

In [25]:
print(results)

[(18, 1.9997455470737915), (17, 1.9997668997668998), (29, 1.9997792494481237), (44, 1.9997831743278405), (23, 1.9997890295358651), (45, 1.9997893406361913), (4, 1.9997979797979797), (39, 1.999805333852443), (16, 1.999808429118774), (26, 1.999810066476733), (31, 1.9998124531132784), (38, 1.9998160750413831), (25, 1.9998168498168498), (12, 1.9998243148278285), (37, 1.9998259355961707), (6, 1.9998299319727892), (13, 1.9998314227916385), (32, 1.9998322710499832), (42, 1.9998335275511903), (20, 1.9998405103668262), (24, 1.9998423955870765), (49, 1.9998454882571075), (11, 1.9998458455372283), (27, 1.9998463901689707), (48, 1.9998523331364442), (43, 1.999854439592431), (21, 1.9998558454663398), (3, 1.9998566308243726), (7, 1.9998570816064027), (19, 1.9998575498575497), (9, 1.9998578535891969), (22, 1.9998578535891969), (41, 1.9998597868760517), (0, 1.999859943977591), (46, 1.9998602375960868), (8, 1.999860529986053), (1, 1.9998623916334113), (5, 1.999864773495605), (14, 1.9998662565199945), (

In [38]:
eliteSize = 10
def selection(results):
    selectionResults = []
    df = pd.DataFrame(np.array(results), columns=["Index","Fitness"])
    df['cum_sum'] = df.Fitness.cumsum()
    df['cum_perc'] = 100*df.cum_sum/df.Fitness.sum()
    
    for i in range(0, eliteSize):
        selectionResults.append(results[i][0])
    for i in range(0, len(results) - eliteSize):
        pick = 100*random.random()
        for i in range(0, len(results)):
            if pick <= df.iat[i,3]:
                selectionResults.append(results[i][0])
                break
    return selectionResults

In [39]:
selectionResults = selection(results)

In [40]:
print(selectionResults)

[18, 17, 29, 44, 23, 45, 4, 39, 16, 26, 16, 21, 19, 31, 33, 39, 12, 7, 33, 31, 18, 41, 16, 35, 16, 9, 48, 23, 23, 16, 12, 45, 37, 30, 25, 31, 25, 40, 22, 7, 19, 46, 47, 24, 19, 10, 19, 21, 23, 19]


In [45]:
def matingPool(genes, selectionResults):
    matingpool = []
    for i in range(0, len(selectionResults)):
        index = selectionResults[i]
        matingpool.append(genes[index])
    return matingpool

In [46]:
matingpool = matingPool(genes, selectionResults)
print(matingpool)

[array([7875.,    0.,    0.]), array([7237.,    0.,    0.]), array([5250.,    0.,    0.]), array([8190.,    0.,    0.]), array([5422.,    0.,    0.]), array([5647.,    0.,    0.]), array([6457.,    0.,    0.]), array([7747.,    0.,    0.]), array([7492.,    0.,    0.]), array([7087.,    0.,    0.]), array([7492.,    0.,    0.]), array([8032.,    0.,    0.]), array([6015.,    0.,    0.]), array([8287.,    0.,    0.]), array([8175.,    0.,    0.]), array([7747.,    0.,    0.]), array([7155.,    0.,    0.]), array([7140.,    0.,    0.]), array([8175.,    0.,    0.]), array([8287.,    0.,    0.]), array([7875.,    0.,    0.]), array([7335.,    0.,    0.]), array([7492.,    0.,    0.]), array([5977.,    0.,    0.]), array([7492.,    0.,    0.]), array([5820.,    0.,    0.]), array([6330.,    0.,    0.]), array([5422.,    0.,    0.]), array([5422.,    0.,    0.]), array([7492.,    0.,    0.]), array([7155.,    0.,    0.]), array([5647.,    0.,    0.]), array([9127.,    0.,    0.]), array([89

In [48]:
def breed(parent1, parent2):
    child = []
    childP1 = []
    childP2 = []
    
    geneA = int(random.random() * len(parent1))
    geneB = int(random.random() * len(parent1))
    
    startGene = min(geneA, geneB)
    endGene = max(geneA, geneB)

    for i in range(startGene, endGene):
        childP1.append(parent1[i])
        
    childP2 = [item for item in parent2 if item not in childP1]

    child = childP1 + childP2
    return child
    
def breedPopulation(matingpool, eliteSize):
    children = []
    length = len(matingpool) - eliteSize
    pool = random.sample(matingpool, len(matingpool))

    for i in range(0,eliteSize):
        children.append(matingpool[i])
    
    for i in range(0, length):
        child = breed(pool[i], pool[len(matingpool)-i-1])
        children.append(child)
    return children

In [49]:
children  = breedPopulation(matingpool, eliteSize)
print(children)

[array([7875.,    0.,    0.]), array([7237.,    0.,    0.]), array([5250.,    0.,    0.]), array([8190.,    0.,    0.]), array([5422.,    0.,    0.]), array([5647.,    0.,    0.]), array([6457.,    0.,    0.]), array([7747.,    0.,    0.]), array([7492.,    0.,    0.]), array([7087.,    0.,    0.]), [6457.0, 8287.0, 0.0, 0.0], [0.0, 6855.0], [5250.0, 0.0, 0.0], [7875.0, 0.0, 0.0], [7140.0, 0.0, 0.0], [5647.0, 0.0, 0.0], [0.0, 7155.0], [7335.0, 0.0, 0.0], [6015.0, 0.0, 0.0], [7492.0, 9195.0, 0.0, 0.0], [7087.0, 0.0, 7875.0], [5722.0, 0.0, 0.0], [5422.0, 0.0, 0.0], [5977.0, 0.0, 8902.0], [8287.0, 0.0, 8190.0], [7492.0, 0.0, 0.0], [5422.0, 0.0, 0.0], [7237.0, 0.0, 8032.0], [0.0, 9127.0], [0.0, 7747.0], [0.0, 6330.0], [5820.0, 6330.0, 0.0, 0.0], [0.0, 4357.0], [0.0, 7492.0], [0.0, 5835.0], [9195.0, 0.0, 0.0], [7492.0, 0.0, 0.0], [0.0, 8175.0], [6330.0, 0.0, 5820.0], [6015.0, 0.0, 0.0], [8175.0, 0.0, 0.0], [9127.0, 0.0, 6015.0], [8032.0, 7237.0, 0.0, 0.0], [5422.0, 6015.0, 0.0, 0.0], [0.0, 

In [50]:
mutationRate = 0.4

def mutate(individual, mutationRate):
    for swapped in range(len(individual)):
        if(random.random() < mutationRate):
            swapWith = int(random.random() * len(individual))
            
            city1 = individual[swapped]
            city2 = individual[swapWith]
            
            individual[swapped] = city2
            individual[swapWith] = city1
    return individual

def mutatePopulation(population, mutationRate):
    mutatedPop = []
    
    for ind in range(0, len(population)):
        mutatedInd = mutate(population[ind], mutationRate)
        mutatedPop.append(mutatedInd)
    return mutatedPop

In [ ]:
def nextGeneration(currentGen, eliteSize, mutationRate):
    popRanked = rankRoutes(currentGen)
    selectionResults = selection(popRanked, eliteSize)
    matingpool = matingPool(currentGen, selectionResults)
    children = breedPopulation(matingpool, eliteSize)
    nextGeneration = mutatePopulation(children, mutationRate)
    return nextGeneration

def geneticAlgorithm(genes, size, eliteSize, mutationRate, generations):
    pop = initialPopulation(popSize, population)
    print("Initial distance: " + str(1 / rankRoutes(pop)[0][1]))
    
    for i in range(0, generations):
        pop = nextGeneration(pop, eliteSize, mutationRate)
    
    print("Final distance: " + str(1 / rankRoutes(pop)[0][1]))
    bestRouteIndex = rankRoutes(pop)[0][0]
    bestRoute = pop[bestRouteIndex]
    return bestRoute